export const routes = [
  "/",
  "/discover",
  "/jobs/saved",
  "/companies",
  "/applications/pipeline",
  "/applications",
  "/interviews",
  "/tasks",
  "/resumes",
  "/cover-letters",
  "/documents",
  "/tools/ats",
  "/tools/matcher",
  "/tools/interview-prep",
  "/contacts",
  "/analytics",
  "/notifications",
  "/settings",
  "/settings/export",
  "/settings/profile",
  "/settings/integrations",
  "/settings/notifications",
  "/settings/billing"
] as const;
